### ISSUE TITLE
manage multi-line content

### ISSUE THREAD

**Issue by guilhem** [themecloud/etcd2envfile#3]

**Comment by guilhem** [comment]
``` go
s = strings.Replace(s,"\n","\\\\n",-1)
```

**Comment by asiragusa** [comment]
The doc states:

> Similar to Environment= but reads the environment variables from a text file. The text file should contain new-line-separated variable assignments. Empty lines, lines without an "=" separator, or lines starting with ; or # will be ignored, which may be used for commenting. A line ending with a backslash will be concatenated with the following one, allowing multiline variable definitions. The parser strips leading and trailing whitespace from the values of assignments, unless you use double quotes (").

So https://github.com/themecloud/etcd2envfile/blob/master/src/etcd2envfile/etcd2envfile.go#L40 will produce a correct environment variable if the etcd key is set up correctly. 

```
echo -ne "foo \\\\\nbar" | etcdctl set /conf/file/key
```
